<a href="https://colab.research.google.com/github/Ravi-Poddar26/missing-values/blob/master/H_M_V(8).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#iterative/mice imputer
import pandas as pd
import numpy as np

from sklearn.linear_model import LinearRegression

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/campusx-official/100-days-of-machine-learning/main/day40-iterative-imputer/50_Startups.csv')

In [ ]:
df.sample(5)

    R&D Spend  Administration  Marketing Spend       State     Profit
3   144372.41       118671.85        383199.62    New York  182901.99
22   73994.56       122782.75        303319.26     Florida  110352.25
9   123334.88       108679.17        304981.62  California  149759.96
24   77044.01        99281.34        140574.81    New York  108552.04
41   27892.92        84710.77        164470.71     Florida   77798.83

In [ ]:
df = df.iloc[:,0:-1]

In [ ]:
df.head()

   R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [ ]:
df.iloc[1,0] = np.nan
df.iloc[3,1] = np.nan
df.iloc[-1,-1] = np.nan

In [ ]:

df.head()

   R&D Spend  Administration  Marketing Spend       State
0  165349.20       136897.80        471784.10    New York
1        NaN       151377.59        443898.53  California
2  153441.51       101145.55        407934.54     Florida
3  144372.41             NaN        383199.62    New York
4  142107.34        91391.77        366168.42     Florida

In [ ]:
# Step 1 - Impute all missing values with mean of respective col

df0 = pd.DataFrame()

df0['R&D Spend'] = df['R&D Spend'].fillna(df['R&D Spend'].mean())
df0['Administration'] = df['Administration'].fillna(df['Administration'].mean())
df0['Marketing Spend'] = df['Marketing Spend'].fillna(df['Marketing Spend'].mean())

In [ ]:

# 0th Iteration
df0

        R&D Spend  Administration  Marketing Spend
0   165349.200000   136897.800000        471784.10
1    71907.817959   151377.590000        443898.53
2   153441.510000   101145.550000        407934.54
3   144372.410000   121399.186327        383199.62
4   142107.340000    91391.770000        366168.42
5   131876.900000    99814.710000        362861.36
6   134615.460000   147198.870000        127716.82
7   130298.130000   145530.060000        323876.68
8   120542.520000   148718.950000        311613.29
9   123334.880000   108679.170000        304981.62
10  101913.080000   110594.110000        229160.95
11  100671.960000    91790.610000        249744.55
12   93863.750000   127320.380000        249839.44
13   91992.390000   135495.070000        252664.93
14  119943.240000   156547.420000        256512.92
15  114523.610000   122616.840000        261776.23
16   78013.110000   121597.550000        264346.06
17   94657.160000   145077.580000        282574.31
18   91749.160000   114175.790000        294919.57
19   86419.700000   153514.110000             0.00
20   76253.860000   113867.300000        298664.47
21   78389.470000   153773.430000        299737.29
22   73994.560000   122782.750000        303319.26
23   67532.530000   105751.030000        304768.73
24   77044.010000    99281.340000        140574.81
25   64664.710000   139553.160000        137962.62
26   75328.870000   144135.980000        134050.07
27   72107.600000   127864.550000        353183.81
28   66051.520000   182645.560000        118148.20
29   65605.480000   153032.060000        107138.38
30   61994.480000   115641.280000         91131.24
31   61136.380000   152701.920000         88218.23
32   63408.860000   129219.610000         46085.25
33   55493.950000   103057.490000        214634.81
34   46426.070000   157693.920000        210797.67
35   46014.020000    85047.440000        205517.64
36   28663.760000   127056.210000        201126.82
37   44069.950000    51283.140000        197029.42
38   20229.590000    65947.930000        185265.10
39   38558.510000    82982.090000        174999.30
40   28754.330000   118546.050000        172795.67
41   27892.920000    84710.770000        164470.71
42   23640.930000    96189.630000        148001.11
43   15505.730000   127382.300000         35534.17
44   22177.740000   154806.140000         28334.72
45    1000.230000   124153.040000          1903.93
46    1315.460000   115816.210000        297114.46
47       0.000000   135426.920000             0.00
48     542.050000    51743.150000             0.00
49       0.000000   116983.800000         45173.06

In [ ]:

# Remove the col1 imputed value
df1 = df0.copy()

df1.iloc[1,0] = np.nan

df1

    R&D Spend  Administration  Marketing Spend
0   165349.20   136897.800000        471784.10
1         NaN   151377.590000        443898.53
2   153441.51   101145.550000        407934.54
3   144372.41   121399.186327        383199.62
4   142107.34    91391.770000        366168.42
5   131876.90    99814.710000        362861.36
6   134615.46   147198.870000        127716.82
7   130298.13   145530.060000        323876.68
8   120542.52   148718.950000        311613.29
9   123334.88   108679.170000        304981.62
10  101913.08   110594.110000        229160.95
11  100671.96    91790.610000        249744.55
12   93863.75   127320.380000        249839.44
13   91992.39   135495.070000        252664.93
14  119943.24   156547.420000        256512.92
15  114523.61   122616.840000        261776.23
16   78013.11   121597.550000        264346.06
17   94657.16   145077.580000        282574.31
18   91749.16   114175.790000        294919.57
19   86419.70   153514.110000             0.00
20   76253.86   113867.300000        298664.47
21   78389.47   153773.430000        299737.29
22   73994.56   122782.750000        303319.26
23   67532.53   105751.030000        304768.73
24   77044.01    99281.340000        140574.81
25   64664.71   139553.160000        137962.62
26   75328.87   144135.980000        134050.07
27   72107.60   127864.550000        353183.81
28   66051.52   182645.560000        118148.20
29   65605.48   153032.060000        107138.38
30   61994.48   115641.280000         91131.24
31   61136.38   152701.920000         88218.23
32   63408.86   129219.610000         46085.25
33   55493.95   103057.490000        214634.81
34   46426.07   157693.920000        210797.67
35   46014.02    85047.440000        205517.64
36   28663.76   127056.210000        201126.82
37   44069.95    51283.140000        197029.42
38   20229.59    65947.930000        185265.10
39   38558.51    82982.090000        174999.30
40   28754.33   118546.050000        172795.67
41   27892.92    84710.770000        164470.71
42   23640.93    96189.630000        148001.11
43   15505.73   127382.300000         35534.17
44   22177.74   154806.140000         28334.72
45    1000.23   124153.040000          1903.93
46    1315.46   115816.210000        297114.46
47       0.00   135426.920000             0.00
48     542.05    51743.150000             0.00
49       0.00   116983.800000         45173.06

In [ ]:

# Use first 3 rows to build a model and use the last for prediction

X = df1.iloc[[0,2,3,4],1:3]
X

   Administration  Marketing Spend
0   136897.800000        471784.10
2   101145.550000        407934.54
3   121399.186327        383199.62
4    91391.770000        366168.42

In [ ]:

y = df1.iloc[[0,2,3,4],0]
y

0    165349.20
2    153441.51
3    144372.41
4    142107.34
Name: R&D Spend, dtype: float64

In [ ]:

lr = LinearRegression()
lr.fit(X,y)
lr.predict(df1.iloc[1,1:].values.reshape(1,2))

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([156866.54270205])

In [ ]:

df1.iloc[1,0] = 23.14

In [ ]:

df1

    R&D Spend  Administration  Marketing Spend
0   165349.20   136897.800000        471784.10
1       23.14   151377.590000        443898.53
2   153441.51   101145.550000        407934.54
3   144372.41   121399.186327        383199.62
4   142107.34    91391.770000        366168.42
5   131876.90    99814.710000        362861.36
6   134615.46   147198.870000        127716.82
7   130298.13   145530.060000        323876.68
8   120542.52   148718.950000        311613.29
9   123334.88   108679.170000        304981.62
10  101913.08   110594.110000        229160.95
11  100671.96    91790.610000        249744.55
12   93863.75   127320.380000        249839.44
13   91992.39   135495.070000        252664.93
14  119943.24   156547.420000        256512.92
15  114523.61   122616.840000        261776.23
16   78013.11   121597.550000        264346.06
17   94657.16   145077.580000        282574.31
18   91749.16   114175.790000        294919.57
19   86419.70   153514.110000             0.00
20   76253.86   113867.300000        298664.47
21   78389.47   153773.430000        299737.29
22   73994.56   122782.750000        303319.26
23   67532.53   105751.030000        304768.73
24   77044.01    99281.340000        140574.81
25   64664.71   139553.160000        137962.62
26   75328.87   144135.980000        134050.07
27   72107.60   127864.550000        353183.81
28   66051.52   182645.560000        118148.20
29   65605.48   153032.060000        107138.38
30   61994.48   115641.280000         91131.24
31   61136.38   152701.920000         88218.23
32   63408.86   129219.610000         46085.25
33   55493.95   103057.490000        214634.81
34   46426.07   157693.920000        210797.67
35   46014.02    85047.440000        205517.64
36   28663.76   127056.210000        201126.82
37   44069.95    51283.140000        197029.42
38   20229.59    65947.930000        185265.10
39   38558.51    82982.090000        174999.30
40   28754.33   118546.050000        172795.67
41   27892.92    84710.770000        164470.71
42   23640.93    96189.630000        148001.11
43   15505.73   127382.300000         35534.17
44   22177.74   154806.140000         28334.72
45    1000.23   124153.040000          1903.93
46    1315.46   115816.210000        297114.46
47       0.00   135426.920000             0.00
48     542.05    51743.150000             0.00
49       0.00   116983.800000         45173.06

In [ ]:

# Remove the col2 imputed value

df1.iloc[3,1] = np.nan

df1

    R&D Spend  Administration  Marketing Spend
0   165349.20       136897.80        471784.10
1       23.14       151377.59        443898.53
2   153441.51       101145.55        407934.54
3   144372.41             NaN        383199.62
4   142107.34        91391.77        366168.42
5   131876.90        99814.71        362861.36
6   134615.46       147198.87        127716.82
7   130298.13       145530.06        323876.68
8   120542.52       148718.95        311613.29
9   123334.88       108679.17        304981.62
10  101913.08       110594.11        229160.95
11  100671.96        91790.61        249744.55
12   93863.75       127320.38        249839.44
13   91992.39       135495.07        252664.93
14  119943.24       156547.42        256512.92
15  114523.61       122616.84        261776.23
16   78013.11       121597.55        264346.06
17   94657.16       145077.58        282574.31
18   91749.16       114175.79        294919.57
19   86419.70       153514.11             0.00
20   76253.86       113867.30        298664.47
21   78389.47       153773.43        299737.29
22   73994.56       122782.75        303319.26
23   67532.53       105751.03        304768.73
24   77044.01        99281.34        140574.81
25   64664.71       139553.16        137962.62
26   75328.87       144135.98        134050.07
27   72107.60       127864.55        353183.81
28   66051.52       182645.56        118148.20
29   65605.48       153032.06        107138.38
30   61994.48       115641.28         91131.24
31   61136.38       152701.92         88218.23
32   63408.86       129219.61         46085.25
33   55493.95       103057.49        214634.81
34   46426.07       157693.92        210797.67
35   46014.02        85047.44        205517.64
36   28663.76       127056.21        201126.82
37   44069.95        51283.14        197029.42
38   20229.59        65947.93        185265.10
39   38558.51        82982.09        174999.30
40   28754.33       118546.05        172795.67
41   27892.92        84710.77        164470.71
42   23640.93        96189.63        148001.11
43   15505.73       127382.30         35534.17
44   22177.74       154806.14         28334.72
45    1000.23       124153.04          1903.93
46    1315.46       115816.21        297114.46
47       0.00       135426.92             0.00
48     542.05        51743.15             0.00
49       0.00       116983.80         45173.06

In [ ]:

# Use last 3 rows to build a model and use the first for prediction
X = df1.iloc[[0,1,2,4],[0,2]]
X

   R&D Spend  Marketing Spend
0  165349.20        471784.10
1      23.14        443898.53
2  153441.51        407934.54
4  142107.34        366168.42

In [ ]:

y = df1.iloc[[0,1,2,4],1]
y

0    136897.80
1    151377.59
2    101145.55
4     91391.77
Name: Administration, dtype: float64

In [ ]:
lr = LinearRegression()
lr.fit(X,y)
lr.predict(df1.iloc[3,[0,2]].values.reshape(1,2))

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([96042.15312646])

In [ ]:

df1.iloc[3,1] = 11.06

In [ ]:

df1

    R&D Spend  Administration  Marketing Spend
0   165349.20       136897.80        471784.10
1       23.14       151377.59        443898.53
2   153441.51       101145.55        407934.54
3   144372.41           11.06        383199.62
4   142107.34        91391.77        366168.42
5   131876.90        99814.71        362861.36
6   134615.46       147198.87        127716.82
7   130298.13       145530.06        323876.68
8   120542.52       148718.95        311613.29
9   123334.88       108679.17        304981.62
10  101913.08       110594.11        229160.95
11  100671.96        91790.61        249744.55
12   93863.75       127320.38        249839.44
13   91992.39       135495.07        252664.93
14  119943.24       156547.42        256512.92
15  114523.61       122616.84        261776.23
16   78013.11       121597.55        264346.06
17   94657.16       145077.58        282574.31
18   91749.16       114175.79        294919.57
19   86419.70       153514.11             0.00
20   76253.86       113867.30        298664.47
21   78389.47       153773.43        299737.29
22   73994.56       122782.75        303319.26
23   67532.53       105751.03        304768.73
24   77044.01        99281.34        140574.81
25   64664.71       139553.16        137962.62
26   75328.87       144135.98        134050.07
27   72107.60       127864.55        353183.81
28   66051.52       182645.56        118148.20
29   65605.48       153032.06        107138.38
30   61994.48       115641.28         91131.24
31   61136.38       152701.92         88218.23
32   63408.86       129219.61         46085.25
33   55493.95       103057.49        214634.81
34   46426.07       157693.92        210797.67
35   46014.02        85047.44        205517.64
36   28663.76       127056.21        201126.82
37   44069.95        51283.14        197029.42
38   20229.59        65947.93        185265.10
39   38558.51        82982.09        174999.30
40   28754.33       118546.05        172795.67
41   27892.92        84710.77        164470.71
42   23640.93        96189.63        148001.11
43   15505.73       127382.30         35534.17
44   22177.74       154806.14         28334.72
45    1000.23       124153.04          1903.93
46    1315.46       115816.21        297114.46
47       0.00       135426.92             0.00
48     542.05        51743.15             0.00
49       0.00       116983.80         45173.06

In [ ]:
# Remove the col3 imputed value
df1.iloc[4,-1] = np.nan

df1

    R&D Spend  Administration  Marketing Spend
0   165349.20       136897.80        471784.10
1       23.14       151377.59        443898.53
2   153441.51       101145.55        407934.54
3   144372.41           11.06        383199.62
4   142107.34        91391.77              NaN
5   131876.90        99814.71        362861.36
6   134615.46       147198.87        127716.82
7   130298.13       145530.06        323876.68
8   120542.52       148718.95        311613.29
9   123334.88       108679.17        304981.62
10  101913.08       110594.11        229160.95
11  100671.96        91790.61        249744.55
12   93863.75       127320.38        249839.44
13   91992.39       135495.07        252664.93
14  119943.24       156547.42        256512.92
15  114523.61       122616.84        261776.23
16   78013.11       121597.55        264346.06
17   94657.16       145077.58        282574.31
18   91749.16       114175.79        294919.57
19   86419.70       153514.11             0.00
20   76253.86       113867.30        298664.47
21   78389.47       153773.43        299737.29
22   73994.56       122782.75        303319.26
23   67532.53       105751.03        304768.73
24   77044.01        99281.34        140574.81
25   64664.71       139553.16        137962.62
26   75328.87       144135.98        134050.07
27   72107.60       127864.55        353183.81
28   66051.52       182645.56        118148.20
29   65605.48       153032.06        107138.38
30   61994.48       115641.28         91131.24
31   61136.38       152701.92         88218.23
32   63408.86       129219.61         46085.25
33   55493.95       103057.49        214634.81
34   46426.07       157693.92        210797.67
35   46014.02        85047.44        205517.64
36   28663.76       127056.21        201126.82
37   44069.95        51283.14        197029.42
38   20229.59        65947.93        185265.10
39   38558.51        82982.09        174999.30
40   28754.33       118546.05        172795.67
41   27892.92        84710.77        164470.71
42   23640.93        96189.63        148001.11
43   15505.73       127382.30         35534.17
44   22177.74       154806.14         28334.72
45    1000.23       124153.04          1903.93
46    1315.46       115816.21        297114.46
47       0.00       135426.92             0.00
48     542.05        51743.15             0.00
49       0.00       116983.80         45173.06

In [ ]:

# Use last 3 rows to build a model and use the first for prediction
X = df1.iloc[0:4,0:2]
X

   R&D Spend  Administration
0  165349.20       136897.80
1      23.14       151377.59
2  153441.51       101145.55
3  144372.41           11.06

In [ ]:

y = df1.iloc[0:4,-1]
y

0    471784.10
1    443898.53
2    407934.54
3    383199.62
Name: Marketing Spend, dtype: float64

In [ ]:
lr = LinearRegression()
lr.fit(X,y)
lr.predict(df1.iloc[4,0:2].values.reshape(1,2))

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([426486.19830015])

In [ ]:
df1.iloc[4,-1] = 31.56

In [ ]:

# After 1st Iteration
df1

    R&D Spend  Administration  Marketing Spend
0   165349.20       136897.80        471784.10
1       23.14       151377.59        443898.53
2   153441.51       101145.55        407934.54
3   144372.41           11.06        383199.62
4   142107.34        91391.77            31.56
5   131876.90        99814.71        362861.36
6   134615.46       147198.87        127716.82
7   130298.13       145530.06        323876.68
8   120542.52       148718.95        311613.29
9   123334.88       108679.17        304981.62
10  101913.08       110594.11        229160.95
11  100671.96        91790.61        249744.55
12   93863.75       127320.38        249839.44
13   91992.39       135495.07        252664.93
14  119943.24       156547.42        256512.92
15  114523.61       122616.84        261776.23
16   78013.11       121597.55        264346.06
17   94657.16       145077.58        282574.31
18   91749.16       114175.79        294919.57
19   86419.70       153514.11             0.00
20   76253.86       113867.30        298664.47
21   78389.47       153773.43        299737.29
22   73994.56       122782.75        303319.26
23   67532.53       105751.03        304768.73
24   77044.01        99281.34        140574.81
25   64664.71       139553.16        137962.62
26   75328.87       144135.98        134050.07
27   72107.60       127864.55        353183.81
28   66051.52       182645.56        118148.20
29   65605.48       153032.06        107138.38
30   61994.48       115641.28         91131.24
31   61136.38       152701.92         88218.23
32   63408.86       129219.61         46085.25
33   55493.95       103057.49        214634.81
34   46426.07       157693.92        210797.67
35   46014.02        85047.44        205517.64
36   28663.76       127056.21        201126.82
37   44069.95        51283.14        197029.42
38   20229.59        65947.93        185265.10
39   38558.51        82982.09        174999.30
40   28754.33       118546.05        172795.67
41   27892.92        84710.77        164470.71
42   23640.93        96189.63        148001.11
43   15505.73       127382.30         35534.17
44   22177.74       154806.14         28334.72
45    1000.23       124153.04          1903.93
46    1315.46       115816.21        297114.46
47       0.00       135426.92             0.00
48     542.05        51743.15             0.00
49       0.00       116983.80         45173.06

In [ ]:

# Subtract 0th iteration from 1st iteration

df1 - df0

       R&D Spend  Administration  Marketing Spend
0       0.000000        0.000000             0.00
1  -71884.677959        0.000000             0.00
2       0.000000        0.000000             0.00
3       0.000000  -121388.126327             0.00
4       0.000000        0.000000       -366136.86
5       0.000000        0.000000             0.00
6       0.000000        0.000000             0.00
7       0.000000        0.000000             0.00
8       0.000000        0.000000             0.00
9       0.000000        0.000000             0.00
10      0.000000        0.000000             0.00
11      0.000000        0.000000             0.00
12      0.000000        0.000000             0.00
13      0.000000        0.000000             0.00
14      0.000000        0.000000             0.00
15      0.000000        0.000000             0.00
16      0.000000        0.000000             0.00
17      0.000000        0.000000             0.00
18      0.000000        0.000000             0.00
19      0.000000        0.000000             0.00
20      0.000000        0.000000             0.00
21      0.000000        0.000000             0.00
22      0.000000        0.000000             0.00
23      0.000000        0.000000             0.00
24      0.000000        0.000000             0.00
25      0.000000        0.000000             0.00
26      0.000000        0.000000             0.00
27      0.000000        0.000000             0.00
28      0.000000        0.000000             0.00
29      0.000000        0.000000             0.00
30      0.000000        0.000000             0.00
31      0.000000        0.000000             0.00
32      0.000000        0.000000             0.00
33      0.000000        0.000000             0.00
34      0.000000        0.000000             0.00
35      0.000000        0.000000             0.00
36      0.000000        0.000000             0.00
37      0.000000        0.000000             0.00
38      0.000000        0.000000             0.00
39      0.000000        0.000000             0.00
40      0.000000        0.000000             0.00
41      0.000000        0.000000             0.00
42      0.000000        0.000000             0.00
43      0.000000        0.000000             0.00
44      0.000000        0.000000             0.00
45      0.000000        0.000000             0.00
46      0.000000        0.000000             0.00
47      0.000000        0.000000             0.00
48      0.000000        0.000000             0.00
49      0.000000        0.000000             0.00

In [ ]:

df2 = df1.copy()

df2.iloc[1,0] = np.nan

df2

    R&D Spend  Administration  Marketing Spend
0   165349.20       136897.80        471784.10
1         NaN       151377.59        443898.53
2   153441.51       101145.55        407934.54
3   144372.41           11.06        383199.62
4   142107.34        91391.77            31.56
5   131876.90        99814.71        362861.36
6   134615.46       147198.87        127716.82
7   130298.13       145530.06        323876.68
8   120542.52       148718.95        311613.29
9   123334.88       108679.17        304981.62
10  101913.08       110594.11        229160.95
11  100671.96        91790.61        249744.55
12   93863.75       127320.38        249839.44
13   91992.39       135495.07        252664.93
14  119943.24       156547.42        256512.92
15  114523.61       122616.84        261776.23
16   78013.11       121597.55        264346.06
17   94657.16       145077.58        282574.31
18   91749.16       114175.79        294919.57
19   86419.70       153514.11             0.00
20   76253.86       113867.30        298664.47
21   78389.47       153773.43        299737.29
22   73994.56       122782.75        303319.26
23   67532.53       105751.03        304768.73
24   77044.01        99281.34        140574.81
25   64664.71       139553.16        137962.62
26   75328.87       144135.98        134050.07
27   72107.60       127864.55        353183.81
28   66051.52       182645.56        118148.20
29   65605.48       153032.06        107138.38
30   61994.48       115641.28         91131.24
31   61136.38       152701.92         88218.23
32   63408.86       129219.61         46085.25
33   55493.95       103057.49        214634.81
34   46426.07       157693.92        210797.67
35   46014.02        85047.44        205517.64
36   28663.76       127056.21        201126.82
37   44069.95        51283.14        197029.42
38   20229.59        65947.93        185265.10
39   38558.51        82982.09        174999.30
40   28754.33       118546.05        172795.67
41   27892.92        84710.77        164470.71
42   23640.93        96189.63        148001.11
43   15505.73       127382.30         35534.17
44   22177.74       154806.14         28334.72
45    1000.23       124153.04          1903.93
46    1315.46       115816.21        297114.46
47       0.00       135426.92             0.00
48     542.05        51743.15             0.00
49       0.00       116983.80         45173.06

In [ ]:

X = df2.iloc[[0,2,3,4],1:3]
y = df2.iloc[[0,2,3,4],0]

lr = LinearRegression()
lr.fit(X,y)
lr.predict(df2.iloc[1,1:].values.reshape(1,2))

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([163966.86330711])

In [ ]:
df2.iloc[1,0] = 23.78

In [ ]:
df2.iloc[3,1] = np.nan
X = df2.iloc[[0,1,2,4],[0,2]]
y = df2.iloc[[0,1,2,4],1]

lr = LinearRegression()
lr.fit(X,y)
lr.predict(df2.iloc[3,[0,2]].values.reshape(1,2))

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([118978.40097602])

In [ ]:
df2.iloc[3,1] = 11.22

In [ ]:
df2.iloc[4,-1] = np.nan

X = df2.iloc[0:4,0:2]
y = df2.iloc[0:4,-1]

lr = LinearRegression()
lr.fit(X,y)
lr.predict(df2.iloc[4,0:2].values.reshape(1,2))

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([426486.1704513])

In [ ]:
df2.iloc[4,-1] = 31.56

In [ ]:
df2

    R&D Spend  Administration  Marketing Spend
0   165349.20       136897.80        471784.10
1       23.78       151377.59        443898.53
2   153441.51       101145.55        407934.54
3   144372.41           11.22        383199.62
4   142107.34        91391.77            31.56
5   131876.90        99814.71        362861.36
6   134615.46       147198.87        127716.82
7   130298.13       145530.06        323876.68
8   120542.52       148718.95        311613.29
9   123334.88       108679.17        304981.62
10  101913.08       110594.11        229160.95
11  100671.96        91790.61        249744.55
12   93863.75       127320.38        249839.44
13   91992.39       135495.07        252664.93
14  119943.24       156547.42        256512.92
15  114523.61       122616.84        261776.23
16   78013.11       121597.55        264346.06
17   94657.16       145077.58        282574.31
18   91749.16       114175.79        294919.57
19   86419.70       153514.11             0.00
20   76253.86       113867.30        298664.47
21   78389.47       153773.43        299737.29
22   73994.56       122782.75        303319.26
23   67532.53       105751.03        304768.73
24   77044.01        99281.34        140574.81
25   64664.71       139553.16        137962.62
26   75328.87       144135.98        134050.07
27   72107.60       127864.55        353183.81
28   66051.52       182645.56        118148.20
29   65605.48       153032.06        107138.38
30   61994.48       115641.28         91131.24
31   61136.38       152701.92         88218.23
32   63408.86       129219.61         46085.25
33   55493.95       103057.49        214634.81
34   46426.07       157693.92        210797.67
35   46014.02        85047.44        205517.64
36   28663.76       127056.21        201126.82
37   44069.95        51283.14        197029.42
38   20229.59        65947.93        185265.10
39   38558.51        82982.09        174999.30
40   28754.33       118546.05        172795.67
41   27892.92        84710.77        164470.71
42   23640.93        96189.63        148001.11
43   15505.73       127382.30         35534.17
44   22177.74       154806.14         28334.72
45    1000.23       124153.04          1903.93
46    1315.46       115816.21        297114.46
47       0.00       135426.92             0.00
48     542.05        51743.15             0.00
49       0.00       116983.80         45173.06

In [ ]:
df2 - df1

    R&D Spend  Administration  Marketing Spend
0        0.00            0.00              0.0
1        0.64            0.00              0.0
2        0.00            0.00              0.0
3        0.00            0.16              0.0
4        0.00            0.00              0.0
5        0.00            0.00              0.0
6        0.00            0.00              0.0
7        0.00            0.00              0.0
8        0.00            0.00              0.0
9        0.00            0.00              0.0
10       0.00            0.00              0.0
11       0.00            0.00              0.0
12       0.00            0.00              0.0
13       0.00            0.00              0.0
14       0.00            0.00              0.0
15       0.00            0.00              0.0
16       0.00            0.00              0.0
17       0.00            0.00              0.0
18       0.00            0.00              0.0
19       0.00            0.00              0.0
20       0.00            0.00              0.0
21       0.00            0.00              0.0
22       0.00            0.00              0.0
23       0.00            0.00              0.0
24       0.00            0.00              0.0
25       0.00            0.00              0.0
26       0.00            0.00              0.0
27       0.00            0.00              0.0
28       0.00            0.00              0.0
29       0.00            0.00              0.0
30       0.00            0.00              0.0
31       0.00            0.00              0.0
32       0.00            0.00              0.0
33       0.00            0.00              0.0
34       0.00            0.00              0.0
35       0.00            0.00              0.0
36       0.00            0.00              0.0
37       0.00            0.00              0.0
38       0.00            0.00              0.0
39       0.00            0.00              0.0
40       0.00            0.00              0.0
41       0.00            0.00              0.0
42       0.00            0.00              0.0
43       0.00            0.00              0.0
44       0.00            0.00              0.0
45       0.00            0.00              0.0
46       0.00            0.00              0.0
47       0.00            0.00              0.0
48       0.00            0.00              0.0
49       0.00            0.00              0.0

In [ ]:
df3 = df2.copy()

df3.iloc[1,0] = np.nan

df3

    R&D Spend  Administration  Marketing Spend
0   165349.20       136897.80        471784.10
1         NaN       151377.59        443898.53
2   153441.51       101145.55        407934.54
3   144372.41           11.22        383199.62
4   142107.34        91391.77            31.56
5   131876.90        99814.71        362861.36
6   134615.46       147198.87        127716.82
7   130298.13       145530.06        323876.68
8   120542.52       148718.95        311613.29
9   123334.88       108679.17        304981.62
10  101913.08       110594.11        229160.95
11  100671.96        91790.61        249744.55
12   93863.75       127320.38        249839.44
13   91992.39       135495.07        252664.93
14  119943.24       156547.42        256512.92
15  114523.61       122616.84        261776.23
16   78013.11       121597.55        264346.06
17   94657.16       145077.58        282574.31
18   91749.16       114175.79        294919.57
19   86419.70       153514.11             0.00
20   76253.86       113867.30        298664.47
21   78389.47       153773.43        299737.29
22   73994.56       122782.75        303319.26
23   67532.53       105751.03        304768.73
24   77044.01        99281.34        140574.81
25   64664.71       139553.16        137962.62
26   75328.87       144135.98        134050.07
27   72107.60       127864.55        353183.81
28   66051.52       182645.56        118148.20
29   65605.48       153032.06        107138.38
30   61994.48       115641.28         91131.24
31   61136.38       152701.92         88218.23
32   63408.86       129219.61         46085.25
33   55493.95       103057.49        214634.81
34   46426.07       157693.92        210797.67
35   46014.02        85047.44        205517.64
36   28663.76       127056.21        201126.82
37   44069.95        51283.14        197029.42
38   20229.59        65947.93        185265.10
39   38558.51        82982.09        174999.30
40   28754.33       118546.05        172795.67
41   27892.92        84710.77        164470.71
42   23640.93        96189.63        148001.11
43   15505.73       127382.30         35534.17
44   22177.74       154806.14         28334.72
45    1000.23       124153.04          1903.93
46    1315.46       115816.21        297114.46
47       0.00       135426.92             0.00
48     542.05        51743.15             0.00
49       0.00       116983.80         45173.06

In [ ]:
X= df3.iloc[[0,2,3,4],1:3]
y = df3.iloc[[0,2,3,4],0]

lr = LinearRegression()
lr.fit(X,y)
lr.predict(df3.iloc[1,1:].values.reshape(1,2))

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([163966.86870596])

In [ ]:
df3.iloc[1,0] = 24.57

In [ ]:

df3.iloc[3,1] = np.nan
X = df3.iloc[[0,1,2,4],[0,2]]
y = df3.iloc[[0,1,2,4],1]

lr = LinearRegression()
lr.fit(X,y)
lr.predict(df3.iloc[3,[0,2]].values.reshape(1,2))

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([118978.41439964])

In [ ]:
df3.iloc[3,1] = 11.37

In [ ]:

df3.iloc[4,-1] = np.nan

X = df3.iloc[0:4,0:2]
y = df3.iloc[0:4,-1]

lr = LinearRegression()
lr.fit(X,y)
lr.predict(df3.iloc[4,0:2].values.reshape(1,2))

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([426486.14275296])

In [ ]:
df3.iloc[4,-1] = 45.53

In [ ]:
df2.iloc[3,1] = 11.22

In [ ]:
df3

    R&D Spend  Administration  Marketing Spend
0   165349.20       136897.80        471784.10
1       24.57       151377.59        443898.53
2   153441.51       101145.55        407934.54
3   144372.41           11.37        383199.62
4   142107.34        91391.77            45.53
5   131876.90        99814.71        362861.36
6   134615.46       147198.87        127716.82
7   130298.13       145530.06        323876.68
8   120542.52       148718.95        311613.29
9   123334.88       108679.17        304981.62
10  101913.08       110594.11        229160.95
11  100671.96        91790.61        249744.55
12   93863.75       127320.38        249839.44
13   91992.39       135495.07        252664.93
14  119943.24       156547.42        256512.92
15  114523.61       122616.84        261776.23
16   78013.11       121597.55        264346.06
17   94657.16       145077.58        282574.31
18   91749.16       114175.79        294919.57
19   86419.70       153514.11             0.00
20   76253.86       113867.30        298664.47
21   78389.47       153773.43        299737.29
22   73994.56       122782.75        303319.26
23   67532.53       105751.03        304768.73
24   77044.01        99281.34        140574.81
25   64664.71       139553.16        137962.62
26   75328.87       144135.98        134050.07
27   72107.60       127864.55        353183.81
28   66051.52       182645.56        118148.20
29   65605.48       153032.06        107138.38
30   61994.48       115641.28         91131.24
31   61136.38       152701.92         88218.23
32   63408.86       129219.61         46085.25
33   55493.95       103057.49        214634.81
34   46426.07       157693.92        210797.67
35   46014.02        85047.44        205517.64
36   28663.76       127056.21        201126.82
37   44069.95        51283.14        197029.42
38   20229.59        65947.93        185265.10
39   38558.51        82982.09        174999.30
40   28754.33       118546.05        172795.67
41   27892.92        84710.77        164470.71
42   23640.93        96189.63        148001.11
43   15505.73       127382.30         35534.17
44   22177.74       154806.14         28334.72
45    1000.23       124153.04          1903.93
46    1315.46       115816.21        297114.46
47       0.00       135426.92             0.00
48     542.05        51743.15             0.00
49       0.00       116983.80         45173.06

In [ ]:
df3 - df2

    R&D Spend  Administration  Marketing Spend
0        0.00            0.00             0.00
1        0.79            0.00             0.00
2        0.00            0.00             0.00
3        0.00            0.15             0.00
4        0.00            0.00            13.97
5        0.00            0.00             0.00
6        0.00            0.00             0.00
7        0.00            0.00             0.00
8        0.00            0.00             0.00
9        0.00            0.00             0.00
10       0.00            0.00             0.00
11       0.00            0.00             0.00
12       0.00            0.00             0.00
13       0.00            0.00             0.00
14       0.00            0.00             0.00
15       0.00            0.00             0.00
16       0.00            0.00             0.00
17       0.00            0.00             0.00
18       0.00            0.00             0.00
19       0.00            0.00             0.00
20       0.00            0.00             0.00
21       0.00            0.00             0.00
22       0.00            0.00             0.00
23       0.00            0.00             0.00
24       0.00            0.00             0.00
25       0.00            0.00             0.00
26       0.00            0.00             0.00
27       0.00            0.00             0.00
28       0.00            0.00             0.00
29       0.00            0.00             0.00
30       0.00            0.00             0.00
31       0.00            0.00             0.00
32       0.00            0.00             0.00
33       0.00            0.00             0.00
34       0.00            0.00             0.00
35       0.00            0.00             0.00
36       0.00            0.00             0.00
37       0.00            0.00             0.00
38       0.00            0.00             0.00
39       0.00            0.00             0.00
40       0.00            0.00             0.00
41       0.00            0.00             0.00
42       0.00            0.00             0.00
43       0.00            0.00             0.00
44       0.00            0.00             0.00
45       0.00            0.00             0.00
46       0.00            0.00             0.00
47       0.00            0.00             0.00
48       0.00            0.00             0.00
49       0.00            0.00             0.00

In [ ]:
#this is also done by scikit learn